version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.34
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.17.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.17.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
  - dependency-name: next
    versions:
    - 10.0.9
    - 10.1.1
    - 10.1.2
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
  - dependency-name: husky
    versions:
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.8
